apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: website-files
        mountPath: /usr/share/nginx/html
      - name: nginx-config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf

  - name: php-fpm
    image: php:7.4-fpm-buster
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && \
        apt-get install -y libpq-dev && \
        docker-php-ext-install pdo pdo_pgsql && \
        php-fpm -F

    ports:
      - containerPort: 9000  # Explicitly expose port 9000
    volumeMounts:
      - name: website-files
        mountPath: /usr/share/nginx/html


  volumes:
    - name: website-files
      hostPath:
        path: /home/sherlock/Kubernetes_learning_hardcore/pods_websites/nginx_test_view
    - name: nginx-config
      configMap:
        name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
